#!/usr/bin/env bash

#Gracefully reloads Gunicorn


# Get the PID of the Gunicorn process
pid=$(pgrep -f 'gunicorn')

# Check if the PID is not empty
if [ -n "$pid" ]; then
    # Send a HUP signal to gracefully restart Gunicorn
    kill -HUP "$pid"
    echo "Gunicorn restarted gracefully."
else
    echo "Gunicorn is not running."
fi
